CREATE SCHEMA health_person_db;

CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    data_nasc DATE NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    sexo VARCHAR(1) NOT NULL,
    altura DOUBLE PRECISION NOT NULL,
    peso DOUBLE PRECISION NOT NULL
);

INSERT INTO pessoa (nome, data_nasc, cpf, sexo, altura, peso) VALUES
('Ana Maria Souza e Silva', '1995-08-14', '111.222.333-44', 'F', 1.65, 62.5),
('Bruno Silva', '1988-03-22', '555.666.777-88', 'M', 1.78, 80.0),
('Camila Silva', '2001-11-05', '999.888.777-66', 'F', 1.70, 68.3);

SELECT * FROM pessoa;